### ISSUE TITLE
Cannot install tre on MacOS

### ISSUE THREAD

**Issue by johnhenry** [dduan/homebrew-formulae#13]
Currently when trying to install tre via brew, the download fails:

```sh
$ brew install dduan/formulae/tre 
==> Installing tre from dduan/formulae
==> Downloading https://github.com/dduan/tre/releases/download/v0.3.0/tre-v0.3.0-x86_64-apple-darwin.tar.
##O=#  #                                                                      
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "tre"
Download failed: https://github.com/dduan/tre/releases/download/v0.3.0/tre-v0.3.0-x86_64-apple-darwin.tar.gz
```

Upon inspection, looks like the requested url, https://github.com/dduan/tre/releases/download/v0.3.0/tre-v0.3.0-x86_64-apple-darwin.tar.gz does not exist, while a similar url, lacking a "v" after "download/" does: https://github.com/dduan/tre/releases/download/0.3.0/tre-v0.3.0-x86_64-apple-darwin.tar.gz

**Comment by dduan** [comment]
no longer an issue. Thanks for reporting!
